import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import {ExploreData} from '../data/ExploreData'
import SmallCard from '@/components/SmallCard'
import { CardData } from '@/data/CardsData'
import MediumCard from '@/components/MediumCard'
import LargeCard from '@/components/LargeCard'
import Footer from '@/components/Footer'
export default function Home() {

  return (
    <>
      <Head>
        <title>Rentals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>

      <main className='max-w-7xl mx-auto px-8 '>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          {/* pulling data from a file */}

          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
          {ExploreData?.map((item)=>(
          <SmallCard 
            key={item.img}
            img={item.img} 
            distance={item.distance} 
            location={item.location}/>
          ))}
          </div>
         
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
          <div className='flex overflow-scroll space-x-3 scrollbar-hide p-3'>
          {CardData.map(item=>(
            <MediumCard key={item.img} img = {item.img} title={item.title}/>
          ))}
          </div>
        </section>

        <LargeCard 
          img='https://links.papareact.com/4cj'
          title='The Awesome Outdoors'
          description='Wishlists created by Rentals'
          buttonText='Get Inspired'
        />
      </main>

      <Footer/>
    </>
  )
}
